In [26]:
import numpy as np
import pandas as pd
df=pd.read_csv("./data/HR.csv")

In [3]:
df.head()

satisfaction_level  last_evaluation  number_project  average_monthly_hours  \
0                0.38             0.53               2                    157   
1                0.80             0.86               5                    262   
2                0.11             0.88               7                    272   
3                0.72             0.87               5                    223   
4                0.37             0.52               2                    159   

   time_spend_company  Work_accident  left  promotion_last_5years department  \
0                   3              0     1                      0      sales   
1                   6              0     1                      0      sales   
2                   4              0     1                      0      sales   
3                   5              0     1                      0      sales   
4                   3              0     1                      0      sales   

   salary  
0     low  
1  medium  
2  medium  
3     low  
4     low

In [5]:
df.skew()

satisfaction_level        -0.476438
last_evaluation          122.482652
number_project             0.337774
average_monthly_hours      0.053225
time_spend_company         1.853530
Work_accident              2.021481
left                       1.229057
promotion_last_5years      6.637677
dtype: float64

In [11]:
df['satisfaction_level'].skew()

-0.47643761717258093

峰态,负值,平均数偏小

In [12]:
df['satisfaction_level'].kurt()

-0.67069593238862524

偏态,0为标准,比正态平缓

In [13]:
import scipy.stats as ss
ss.norm

In [14]:
ss.norm.stats(moments = 'mvsk')

(array(0.0), array(1.0), array(0.0), array(0.0))

In [15]:
ss.norm.pdf(0.0)

0.3989422804014327

0时的值

In [16]:
ss.norm.ppf(0.9)

1.2815515655446004

ss.norm.ppf(),输入值n为0-1之间,负无穷累计到n,x应为多少

In [18]:
ss.norm.cdf(2)

0.97724986805182079


cdf,负无穷积到2,概率0.97

In [19]:
ss.norm.cdf(2)-ss.norm.cdf(-2)

0.95449973610364158

正2倍标准差-负2倍标准差,中间的概率是0.95

In [20]:
ss.norm.rvs(size=10)

array([ 0.16344469,  0.44565915, -0.38347836, -0.82343213, -0.29735504,
        1.08800445,  0.30026272, -1.09637475,  0.49192196,  0.79821641])

10个正态分布

In [21]:
ss.chi2

In [22]:
ss.t  #t

In [23]:
ss.f  #f

In [24]:
df.sample(n=10)

satisfaction_level  last_evaluation  number_project  \
1223                 0.75             0.89               4   
486                  0.38             0.49               2   
8341                 0.83             0.84               4   
328                  0.10             0.85               6   
1769                 0.40             0.47               2   
8819                 0.63             0.80               3   
4653                 0.89             0.89               3   
11251                0.78             0.50               5   
1227                 0.39             0.54               2   
8731                 0.68             0.61               4   

       average_monthly_hours  time_spend_company  Work_accident  left  \
1223                     228                   5              0     1   
486                      135                   3              0     1   
8341                     206                   2              0     0   
328                      266                   4              0     1   
1769                     144                   3              1     1   
8819                     267                   3              0     0   
4653                     138                   2              0     0   
11251                    247                   4              0     0   
1227                     131                   3              0     1   
8731                     147                   3              0     0   

       promotion_last_5years   department  salary  
1223                       0      support     low  
486                        0   accounting     low  
8341                       0        sales  medium  
328                        0        sales     low  
1769                       0        sales     low  
8819                       0    technical     low  
4653                       0        RandD  medium  
11251                      0  product_mng  medium  
1227                       0    marketing     low  
8731                       0   accounting  medium

df抽10个样

In [25]:
df.sample(frac=0.001)

satisfaction_level  last_evaluation  number_project  \
2275                 0.94             0.74               5   
13145                0.75             0.63               4   
7117                 0.95             0.50               4   
13385                0.61             0.97               6   
10490                0.50             0.70               4   
971                  0.72             1.00               5   
671                  0.11             0.94               6   
10968                0.63             0.91               4   
8032                 0.58             0.71               3   
9158                 0.44             0.67               5   
2926                 0.82             0.84               3   
8125                 0.98             0.64               4   
9958                 0.91             0.59               5   
8176                 0.74             0.69               4   
8100                 0.71             0.53               5   

       average_monthly_hours  time_spend_company  Work_accident  left  \
2275                     171                   3              0     0   
13145                    209                   3              0     0   
7117                     186                   3              1     0   
13385                    286                   4              0     0   
10490                    135                   3              0     0   
971                      264                   5              0     1   
671                      264                   4              0     1   
10968                    252                   3              1     0   
8032                     230                   3              1     0   
9158                     170                   3              1     0   
2926                     139                   2              1     0   
8125                     134                   3              1     0   
9958                     179                   3              0     0   
8176                     244                   2              0     0   
8100                     162                   2              0     0   

       promotion_last_5years   department  salary  
2275                       0           IT     low  
13145                      1        sales  medium  
7117                       0        sales     low  
13385                      0  product_mng  medium  
10490                      0           hr     low  
971                        0    technical  medium  
671                        0           IT     low  
10968                      0      support  medium  
8032                       0        sales  medium  
9158                       0    marketing  medium  
2926                       0        sales     low  
8125                       0    technical     low  
9958                       0           hr     low  
8176                       0        sales     low  
8100                       0        sales     low

In [26]:
df['satisfaction_level'].sample(10)

5740     0.51
3964     0.95
5125     0.98
13145    0.75
11285    0.64
10631    0.60
1498     0.42
13932    0.98
5521     0.72
3992     0.53
Name: satisfaction_level, dtype: float64

In [ ]:
df[']

In [4]:
sl_s = df['satisfaction_level']

In [7]:
sl_s.isnull()

0        False
1        False
2        False
3        False
4        False
5        False
6        False
7        False
8        False
9        False
10       False
11       False
12       False
13       False
14       False
15       False
16       False
17       False
18       False
19       False
20       False
21       False
22       False
23       False
24       False
25       False
26       False
27       False
28       False
29       False
         ...  
14972    False
14973    False
14974    False
14975    False
14976    False
14977    False
14978    False
14979    False
14980    False
14981    False
14982    False
14983    False
14984    False
14985    False
14986    False
14987    False
14988    False
14989    False
14990    False
14991    False
14992    False
14993    False
14994    False
14995    False
14996    False
14997    False
14998    False
14999     True
15000     True
15001    False
Name: satisfaction_level, Length: 15002, dtype: bool

In [8]:
sl_s[sl_s.isnull()]

14999   NaN
15000   NaN
Name: satisfaction_level, dtype: float64

In [9]:
df[df['satisfaction_level'].isnull()]

satisfaction_level  last_evaluation  number_project  \
14999                 NaN             0.52               2   
15000                 NaN        999999.00               2   

       average_monthly_hours  time_spend_company  Work_accident  left  \
14999                    158                   3              0     1   
15000                    158                   3              0     1   

       promotion_last_5years department salary  
14999                      0    support    low  
15000                      0       sale    low

In [13]:
sl_s= sl_s.dropna()  #丢弃异常值

In [ ]:
#sl_s=s.fillna()  填充异常值

In [14]:
sl_s.mean()

0.61283933333333329

In [15]:
sl_s.std()

0.24862338135944925

In [16]:
sl_s.max()

1.0

In [17]:
sl_s.min()

0.089999999999999997

In [18]:
sl_s.median()

0.64

In [19]:
sl_s.quantile(q = 0.25)

0.44

In [20]:
sl_s.quantile(q = 0.75)

0.82

In [22]:
sl_s.quantile(q=0.5)

0.64

In [23]:
sl_s.skew()

-0.47643761717258093

In [20]:
sl_s.quantile(q = 0.75)

0.82

In [24]:
sl_s.kurt()

-0.67069593238862524

In [27]:
np.histogram(sl_s.values,bins = np.arange(0.0,1.1,0.1))
#值,bins切分临界值

(array([ 195, 1214,  532,  974, 1668, 2146, 1973, 2074, 2220, 2004], dtype=int64),
 array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ]))

In [28]:
le_s = df['last_evaluation']

In [29]:
le_s[le_s.isnull()]

Series([], Name: last_evaluation, dtype: float64)

In [30]:
le_s.mean()

67.373732169044118

In [31]:
le_s.median()

0.72

In [32]:
le_s.min()

0.35999999999999999

In [33]:
le_s.skew()

122.48265175204614

In [34]:
le_s.kurt()

15001.999986807796

In [35]:
le_s[le_s>1]

15000    999999.0
Name: last_evaluation, dtype: float64

In [ ]:
le_s = le_s.drop([le_s>1])

In [37]:
q_low = le_s.quantile(q = 0.25)

In [38]:
q_high = le_s.quantile(q = 0.75)

In [39]:
q_interval = q_high - q_low

In [40]:
k = 1.5

In [70]:
le_s = le_s[le_s<q_high+k*q_interval][le_s>q_low-k*q_interval]

In [71]:
le_s

0        0.53
1        0.86
2        0.88
3        0.87
4        0.52
5        0.50
6        0.77
7        0.85
8        1.00
9        0.53
10       0.54
11       0.81
12       0.92
13       0.55
14       0.56
15       0.54
16       0.47
17       0.99
18       0.51
19       0.89
20       0.83
21       0.55
22       0.95
23       0.57
24       0.53
25       0.92
26       0.87
27       0.49
28       0.46
29       0.50
         ... 
14971    0.45
14972    0.97
14973    0.52
14974    0.54
14975    0.79
14976    0.47
14977    0.85
14978    0.47
14979    0.93
14980    0.89
14981    0.93
14982    0.49
14983    0.84
14984    0.56
14985    0.99
14986    0.85
14987    0.70
14988    0.55
14989    0.57
14990    0.88
14991    0.81
14992    0.48
14993    0.83
14994    0.57
14995    0.48
14996    0.53
14997    0.96
14998    0.52
14999    0.52
15001    0.40
Name: last_evaluation, Length: 15001, dtype: float64

In [43]:
np.histogram(le_s.values,bins = np.arange(0.0,1.1,0.1))

(array([   0,    0,    0,  179, 1390, 3396, 2234, 2062, 2752, 2988], dtype=int64),
 array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ]))

In [44]:
le_s.mean()

0.71606759549363375

In [45]:
le_s.std()

0.17118464250786233

In [46]:
le_s.median()

0.72

In [47]:
le_s.max()

1.0

In [48]:
le_s.skew()

-0.026532537468725789

In [49]:
le_s.kurt()

-1.2390454655108427

In [51]:
df.head()

satisfaction_level  last_evaluation  number_project  average_monthly_hours  \
0                0.38             0.53               2                    157   
1                0.80             0.86               5                    262   
2                0.11             0.88               7                    272   
3                0.72             0.87               5                    223   
4                0.37             0.52               2                    159   

   time_spend_company  Work_accident  left  promotion_last_5years department  \
0                   3              0     1                      0      sales   
1                   6              0     1                      0      sales   
2                   4              0     1                      0      sales   
3                   5              0     1                      0      sales   
4                   3              0     1                      0      sales   

   salary  
0     low  
1  medium  
2  medium  
3     low  
4     low

In [52]:
np_s = df['number_project']

In [54]:
np_s.value_counts()  #次数

4    4365
3    4055
5    2761
2    2391
6    1174
7     256
Name: number_project, dtype: int64

In [55]:
np_s.value_counts(normalize=True)  #比例

4    0.290961
3    0.270297
5    0.184042
2    0.159379
6    0.078256
7    0.017064
Name: number_project, dtype: float64

In [56]:
np_s.value_counts(normalize=True).sort_index()  

2    0.159379
3    0.270297
4    0.290961
5    0.184042
6    0.078256
7    0.017064
Name: number_project, dtype: float64

In [77]:
amh_s = df['average_monthly_hours']

In [78]:
amh_s.mean()

201.04172776963071

In [79]:
amh_s.describe()

count    15002.000000
mean       201.041728
std         49.941815
min         96.000000
25%        156.000000
50%        200.000000
75%        245.000000
max        310.000000
Name: average_monthly_hours, dtype: float64

In [80]:
amh_s.skew()

0.053224587799163038

In [81]:
amh_s.kurt()

-1.1350158577565719

In [84]:
len(amh_s)

15002

In [92]:
amh_s[amh_s<amh_s.quantile(0.75)+1.5*(amh_s.quantile(0.75)-amh_s.quantile(0.25))][amh_s>amh_s.quantile(0.25)-1.5*(amh_s.quantile(0.75)-amh_s.quantile(0.25))]

0        157
1        262
2        272
3        223
4        159
5        153
6        247
7        259
8        224
9        142
10       135
11       305
12       234
13       148
14       137
15       143
16       160
17       255
18       160
19       262
20       282
21       147
22       304
23       139
24       158
25       242
26       239
27       135
28       128
29       132
        ... 
14972    310
14973    143
14974    153
14975    310
14976    136
14977    251
14978    144
14979    296
14980    238
14981    162
14982    137
14983    257
14984    148
14985    254
14986    247
14987    206
14988    145
14989    159
14990    228
14991    257
14992    155
14993    293
14994    151
14995    160
14996    143
14997    280
14998    158
14999    158
15000    158
15001    158
Name: average_monthly_hours, Length: 15002, dtype: int64

In [95]:
amh_s = amh_s[amh_s<amh_s.quantile(0.75)+1.5*(amh_s.quantile(0.75)-amh_s.quantile(0.25))][amh_s>amh_s.quantile(0.25)-1.5*(amh_s.quantile(0.75)-amh_s.quantile(0.25))]

In [90]:
amh_s[amh_s>amh_s.quantile(0.25)-1.5*(amh_s.quantile(0.75)-amh_s.quantile(0.25))]

0        157
1        262
2        272
3        223
4        159
5        153
6        247
7        259
8        224
9        142
10       135
11       305
12       234
13       148
14       137
15       143
16       160
17       255
18       160
19       262
20       282
21       147
22       304
23       139
24       158
25       242
26       239
27       135
28       128
29       132
        ... 
14972    310
14973    143
14974    153
14975    310
14976    136
14977    251
14978    144
14979    296
14980    238
14981    162
14982    137
14983    257
14984    148
14985    254
14986    247
14987    206
14988    145
14989    159
14990    228
14991    257
14992    155
14993    293
14994    151
14995    160
14996    143
14997    280
14998    158
14999    158
15000    158
15001    158
Name: average_monthly_hours, Length: 15002, dtype: int64

In [ ]:
dd

In [96]:
len(amh_s)

15002

In [97]:
np.histogram(amh_s.values,bins=10)

(array([ 367, 1240, 2736, 1722, 1628, 1712, 1906, 2240, 1127,  324], dtype=int64),
 array([  96. ,  117.4,  138.8,  160.2,  181.6,  203. ,  224.4,  245.8,
         267.2,  288.6,  310. ]))

In [100]:
np.histogram(amh_s.values,bins=np.arange(amh_s.min(),amh_s.max()+10,10))  #左闭右开

(array([ 168,  171,  147,  807, 1153, 1234, 1075,  824,  818,  758,  751,
         738,  856,  824,  987, 1002, 1045,  935,  299,  193,  131,   86], dtype=int64),
 array([ 96, 106, 116, 126, 136, 146, 156, 166, 176, 186, 196, 206, 216,
        226, 236, 246, 256, 266, 276, 286, 296, 306, 316], dtype=int64))

In [103]:
amh_s.value_counts(bins=np.arange(amh_s.min(),amh_s.max()+10,10)).sort_index()     #左开右闭

(95.999, 106.0]     187
(106.0, 116.0]      162
(116.0, 126.0]      162
(126.0, 136.0]      886
(136.0, 146.0]     1159
(146.0, 156.0]     1277
(156.0, 166.0]      995
(166.0, 176.0]      832
(176.0, 186.0]      813
(186.0, 196.0]      761
(196.0, 206.0]      755
(206.0, 216.0]      731
(216.0, 226.0]      873
(226.0, 236.0]      814
(236.0, 246.0]     1006
(246.0, 256.0]      987
(256.0, 266.0]     1063
(266.0, 276.0]      860
(276.0, 286.0]      319
(286.0, 296.0]      164
(296.0, 306.0]      128
(306.0, 316.0]       68
Name: average_monthly_hours, dtype: int64

In [104]:
tsc_s = df['time_spend_company']

In [106]:
tsc_s.describe()

count    15002.000000
mean         3.498067
std          1.460053
min          2.000000
25%          3.000000
50%          3.000000
75%          4.000000
max         10.000000
Name: time_spend_company, dtype: float64

In [107]:
tsc_s.value_counts().sort_index()  

2     3245
3     6445
4     2557
5     1473
6      718
7      188
8      162
10     214
Name: time_spend_company, dtype: int64

In [108]:
wa_s = df['Work_accident']

In [110]:
wa_s.value_counts()   
#大部分人没有发生事故

0    12833
1     2169
Name: Work_accident, dtype: int64

In [111]:
wa_s.describe()

count    15002.000000
mean         0.144581
std          0.351689
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max          1.000000
Name: Work_accident, dtype: float64

In [112]:
l_s = df['left']

In [114]:
l_s.value_counts()

0    11428
1     3574
Name: left, dtype: int64

In [115]:
pl5_s = df['promotion_last_5years']

In [116]:
pl5_s.value_counts()

0    14683
1      319
Name: promotion_last_5years, dtype: int64

In [117]:
s_s = df['salary']

In [118]:
s_s.value_counts()

low       7318
medium    6446
high      1237
nme          1
Name: salary, dtype: int64

In [119]:
s_s

0           low
1        medium
2        medium
3           low
4           low
5           low
6           low
7           low
8           low
9           low
10          low
11          low
12          low
13          low
14          low
15          low
16          low
17          low
18          low
19          low
20          low
21          low
22          low
23          low
24          low
25          low
26          low
27          low
28          low
29          low
          ...  
14972    medium
14973    medium
14974    medium
14975    medium
14976    medium
14977    medium
14978    medium
14979    medium
14980      high
14981       low
14982    medium
14983    medium
14984    medium
14985    medium
14986       low
14987       low
14988       low
14989       low
14990       low
14991       low
14992       low
14993       low
14994       low
14995       low
14996       low
14997       low
14998       low
14999       low
15000       low
15001       nme
Name: salary, Length: 15

In [121]:
s_s.where(s_s=='nme')

0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
5        NaN
6        NaN
7        NaN
8        NaN
9        NaN
10       NaN
11       NaN
12       NaN
13       NaN
14       NaN
15       NaN
16       NaN
17       NaN
18       NaN
19       NaN
20       NaN
21       NaN
22       NaN
23       NaN
24       NaN
25       NaN
26       NaN
27       NaN
28       NaN
29       NaN
        ... 
14972    NaN
14973    NaN
14974    NaN
14975    NaN
14976    NaN
14977    NaN
14978    NaN
14979    NaN
14980    NaN
14981    NaN
14982    NaN
14983    NaN
14984    NaN
14985    NaN
14986    NaN
14987    NaN
14988    NaN
14989    NaN
14990    NaN
14991    NaN
14992    NaN
14993    NaN
14994    NaN
14995    NaN
14996    NaN
14997    NaN
14998    NaN
14999    NaN
15000    NaN
15001    nme
Name: salary, Length: 15002, dtype: object

In [122]:
s_s.where(s_s!='nme')

0           low
1        medium
2        medium
3           low
4           low
5           low
6           low
7           low
8           low
9           low
10          low
11          low
12          low
13          low
14          low
15          low
16          low
17          low
18          low
19          low
20          low
21          low
22          low
23          low
24          low
25          low
26          low
27          low
28          low
29          low
          ...  
14972    medium
14973    medium
14974    medium
14975    medium
14976    medium
14977    medium
14978    medium
14979    medium
14980      high
14981       low
14982    medium
14983    medium
14984    medium
14985    medium
14986       low
14987       low
14988       low
14989       low
14990       low
14991       low
14992       low
14993       low
14994       low
14995       low
14996       low
14997       low
14998       low
14999       low
15000       low
15001       NaN
Name: salary, Length: 15

In [123]:
s_s.where(s_s!='nme').dropna()

0           low
1        medium
2        medium
3           low
4           low
5           low
6           low
7           low
8           low
9           low
10          low
11          low
12          low
13          low
14          low
15          low
16          low
17          low
18          low
19          low
20          low
21          low
22          low
23          low
24          low
25          low
26          low
27          low
28          low
29          low
          ...  
14971    medium
14972    medium
14973    medium
14974    medium
14975    medium
14976    medium
14977    medium
14978    medium
14979    medium
14980      high
14981       low
14982    medium
14983    medium
14984    medium
14985    medium
14986       low
14987       low
14988       low
14989       low
14990       low
14991       low
14992       low
14993       low
14994       low
14995       low
14996       low
14997       low
14998       low
14999       low
15000       low
Name: salary, Length: 15

In [124]:
d_s = df['department']

In [126]:
d_s.value_counts(normalize=True)

sales          0.275963
technical      0.181309
support        0.148647
IT             0.081789
product_mng    0.060125
marketing      0.057192
RandD          0.052460
accounting     0.051127
hr             0.049260
management     0.041994
sale           0.000133
Name: department, dtype: float64

In [128]:
d_s = d_s.where(d_s!='sales').dropna()

In [129]:
d_s.value_counts(normalize=True)

technical      0.250414
support        0.205303
IT             0.112963
product_mng    0.083042
marketing      0.078991
RandD          0.072454
accounting     0.070613
hr             0.068035
management     0.058000
sale           0.000184
Name: department, dtype: float64

In [142]:
df = pd.read_csv('./data/HR.csv')

In [143]:
df

satisfaction_level  last_evaluation  number_project  \
0                    0.38             0.53               2   
1                    0.80             0.86               5   
2                    0.11             0.88               7   
3                    0.72             0.87               5   
4                    0.37             0.52               2   
5                    0.41             0.50               2   
6                    0.10             0.77               6   
7                    0.92             0.85               5   
8                    0.89             1.00               5   
9                    0.42             0.53               2   
10                   0.45             0.54               2   
11                   0.11             0.81               6   
12                   0.84             0.92               4   
13                   0.41             0.55               2   
14                   0.36             0.56               2   
15                   0.38             0.54               2   
16                   0.45             0.47               2   
17                   0.78             0.99               4   
18                   0.45             0.51               2   
19                   0.76             0.89               5   
20                   0.11             0.83               6   
21                   0.38             0.55               2   
22                   0.09             0.95               6   
23                   0.46             0.57               2   
24                   0.40             0.53               2   
25                   0.89             0.92               5   
26                   0.82             0.87               4   
27                   0.40             0.49               2   
28                   0.41             0.46               2   
29                   0.38             0.50               2   
...                   ...              ...             ...   
14972                0.11             0.97               6   
14973                0.36             0.52               2   
14974                0.36             0.54               2   
14975                0.10             0.79               7   
14976                0.40             0.47               2   
14977                0.81             0.85               4   
14978                0.40             0.47               2   
14979                0.09             0.93               6   
14980                0.76             0.89               5   
14981                0.73             0.93               5   
14982                0.38             0.49               2   
14983                0.72             0.84               5   
14984                0.40             0.56               2   
14985                0.91             0.99               5   
14986                0.85             0.85               4   
14987                0.90             0.70               5   
14988                0.46             0.55               2   
14989                0.43             0.57               2   
14990                0.89             0.88               5   
14991                0.09             0.81               6   
14992                0.40             0.48               2   
14993                0.76             0.83               6   
14994                0.40             0.57               2   
14995                0.37             0.48               2   
14996                0.37             0.53               2   
14997                0.11             0.96               6   
14998                0.37             0.52               2   
14999                 NaN             0.52               2   
15000                 NaN        999999.00               2   
15001                0.70             0.40               2   

       average_monthly_hours  time_spend_company  Work_accident  left  \
0                        157                   3              0     1   
1               

In [144]:
df = df.dropna(axis = 0,how='any')
#how一行全为空删除,any有一为空删

In [145]:
len(df)

15000

In [146]:
df

satisfaction_level  last_evaluation  number_project  \
0                    0.38             0.53               2   
1                    0.80             0.86               5   
2                    0.11             0.88               7   
3                    0.72             0.87               5   
4                    0.37             0.52               2   
5                    0.41             0.50               2   
6                    0.10             0.77               6   
7                    0.92             0.85               5   
8                    0.89             1.00               5   
9                    0.42             0.53               2   
10                   0.45             0.54               2   
11                   0.11             0.81               6   
12                   0.84             0.92               4   
13                   0.41             0.55               2   
14                   0.36             0.56               2   
15                   0.38             0.54               2   
16                   0.45             0.47               2   
17                   0.78             0.99               4   
18                   0.45             0.51               2   
19                   0.76             0.89               5   
20                   0.11             0.83               6   
21                   0.38             0.55               2   
22                   0.09             0.95               6   
23                   0.46             0.57               2   
24                   0.40             0.53               2   
25                   0.89             0.92               5   
26                   0.82             0.87               4   
27                   0.40             0.49               2   
28                   0.41             0.46               2   
29                   0.38             0.50               2   
...                   ...              ...             ...   
14970                0.78             0.93               4   
14971                0.39             0.45               2   
14972                0.11             0.97               6   
14973                0.36             0.52               2   
14974                0.36             0.54               2   
14975                0.10             0.79               7   
14976                0.40             0.47               2   
14977                0.81             0.85               4   
14978                0.40             0.47               2   
14979                0.09             0.93               6   
14980                0.76             0.89               5   
14981                0.73             0.93               5   
14982                0.38             0.49               2   
14983                0.72             0.84               5   
14984                0.40             0.56               2   
14985                0.91             0.99               5   
14986                0.85             0.85               4   
14987                0.90             0.70               5   
14988                0.46             0.55               2   
14989                0.43             0.57               2   
14990                0.89             0.88               5   
14991                0.09             0.81               6   
14992                0.40             0.48               2   
14993                0.76             0.83               6   
14994                0.40             0.57               2   
14995                0.37             0.48               2   
14996                0.37             0.53               2   
14997                0.11             0.96               6   
14998                0.37             0.52               2   
15001                0.70             0.40               2   

       average_monthly_hours  time_spend_company  Work_accident  left  \
0                        157                   3              0     1   
1               

In [150]:
df = df[df['last_evaluation']<=1][df['salary']!='nme'][df['department']!='sale']

In [151]:
df

satisfaction_level  last_evaluation  number_project  \
0                    0.38             0.53               2   
1                    0.80             0.86               5   
2                    0.11             0.88               7   
3                    0.72             0.87               5   
4                    0.37             0.52               2   
5                    0.41             0.50               2   
6                    0.10             0.77               6   
7                    0.92             0.85               5   
8                    0.89             1.00               5   
9                    0.42             0.53               2   
10                   0.45             0.54               2   
11                   0.11             0.81               6   
12                   0.84             0.92               4   
13                   0.41             0.55               2   
14                   0.36             0.56               2   
15                   0.38             0.54               2   
16                   0.45             0.47               2   
17                   0.78             0.99               4   
18                   0.45             0.51               2   
19                   0.76             0.89               5   
20                   0.11             0.83               6   
21                   0.38             0.55               2   
22                   0.09             0.95               6   
23                   0.46             0.57               2   
24                   0.40             0.53               2   
25                   0.89             0.92               5   
26                   0.82             0.87               4   
27                   0.40             0.49               2   
28                   0.41             0.46               2   
29                   0.38             0.50               2   
...                   ...              ...             ...   
14969                0.43             0.46               2   
14970                0.78             0.93               4   
14971                0.39             0.45               2   
14972                0.11             0.97               6   
14973                0.36             0.52               2   
14974                0.36             0.54               2   
14975                0.10             0.79               7   
14976                0.40             0.47               2   
14977                0.81             0.85               4   
14978                0.40             0.47               2   
14979                0.09             0.93               6   
14980                0.76             0.89               5   
14981                0.73             0.93               5   
14982                0.38             0.49               2   
14983                0.72             0.84               5   
14984                0.40             0.56               2   
14985                0.91             0.99               5   
14986                0.85             0.85               4   
14987                0.90             0.70               5   
14988                0.46             0.55               2   
14989                0.43             0.57               2   
14990                0.89             0.88               5   
14991                0.09             0.81               6   
14992                0.40             0.48               2   
14993                0.76             0.83               6   
14994                0.40             0.57               2   
14995                0.37             0.48               2   
14996                0.37             0.53               2   
14997                0.11             0.96               6   
14998                0.37             0.52               2   

       average_monthly_hours  time_spend_company  Work_accident  left  \
0                        157                   3              0     1   
1               

In [154]:
df[['salary','department']]

salary  department
0         low       sales
1      medium       sales
2      medium       sales
3         low       sales
4         low       sales
5         low       sales
6         low       sales
7         low       sales
8         low       sales
9         low       sales
10        low       sales
11        low       sales
12        low       sales
13        low       sales
14        low       sales
15        low       sales
16        low       sales
17        low       sales
18        low       sales
19        low       sales
20        low       sales
21        low       sales
22        low       sales
23        low       sales
24        low       sales
25        low       sales
26        low       sales
27        low       sales
28        low  accounting
29        low  accounting
...       ...         ...
14969  medium       sales
14970  medium       sales
14971  medium       sales
14972  medium  accounting
14973  medium  accounting
14974  medium  accounting
14975  medium          hr
14976  medium          hr
14977  medium          hr
14978  medium          hr
14979  medium   technical
14980    high   technical
14981     low   technical
14982  medium   technical
14983  medium   technical
14984  medium   technical
14985  medium   technical
14986     low   technical
14987     low   technical
14988     low   technical
14989     low   technical
14990     low     support
14991     low     support
14992     low     support
14993     low     support
14994     low     support
14995     low     support
14996     low     support
14997     low     support
14998     low     support

[14999 rows x 2 columns]

In [155]:
df.groupby('department').mean()

satisfaction_level  last_evaluation  number_project  \
department                                                         
IT                     0.618142         0.716830        3.816626   
RandD                  0.619822         0.712122        3.853875   
accounting             0.582151         0.717718        3.825293   
hr                     0.598809         0.708850        3.654939   
management             0.621349         0.724000        3.860317   
marketing              0.618601         0.715886        3.687646   
product_mng            0.619634         0.714756        3.807095   
sales                  0.614447         0.709717        3.776329   
support                0.618300         0.723109        3.803948   
technical              0.607897         0.721099        3.877941   

             average_monthly_hours  time_spend_company  Work_accident  \
department                                                              
IT                      202.215974            3.468623       0.133659   
RandD                   200.800508            3.367217       0.170267   
accounting              201.162973            3.522816       0.125163   
hr                      198.684709            3.355886       0.120433   
management              201.249206            4.303175       0.163492   
marketing               199.385781            3.569930       0.160839   
product_mng             199.965632            3.475610       0.146341   
sales                   200.911353            3.534058       0.141787   
support                 200.758188            3.393001       0.154778   
technical               202.497426            3.411397       0.140074   

                 left  promotion_last_5years  
department                                    
IT           0.222494               0.002445  
RandD        0.153748               0.034307  
accounting   0.265971               0.018253  
hr           0.290934               0.020298  
management   0.144444               0.109524  
marketing    0.236597               0.050117  
product_mng  0.219512               0.000000  
sales        0.244928               0.024155  
support      0.248991               0.008973  
technical    0.256250               0.010294

In [157]:
df.loc[:,['last_evaluation','department']].groupby('department').mean()

last_evaluation
department                  
IT                  0.716830
RandD               0.712122
accounting          0.717718
hr                  0.708850
management          0.724000
marketing           0.715886
product_mng         0.714756
sales               0.709717
support             0.723109
technical           0.721099

In [158]:
 df.loc[:,['average_monthly_hours','department']].groupby('department')['average_monthly_hours'].apply(lambda x:x.max()-x.min())

department
IT             212
RandD          210
accounting     213
hr             212
management     210
marketing      214
product_mng    212
sales          214
support        214
technical      213
Name: average_monthly_hours, dtype: int64