### 特征工程

数据和特征决定了机器学习的上限,模型和算法只能逼近上限


In [109]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns
import scipy.stats as ss
%matplotlib inline 

### 数据样本采集
抽样  具有代表性  
样本比例要平衡

### 异常值(空值)处理
pandas: isnull()/duplicated()  
drop()/dropna()/drop_duplicated()  
fillna()  
interpolate()

In [110]:
df = pd.DataFrame({"A": ["a0", "a1", "a1", "a2", "a3", "a4"], "B": ["b0", "b1", "b2", "b2", "b3", None],
                   "C": [1, 2, None, 3, 4, 5], "D": [0.1, 10.2, 11.4, 8.9, 9.1, 12], "E": [10, 19, 32, 25, 8, None],
                   "F": ["f0", "f1", "g2", "f3", "f4", "f5"]})
df

A     B    C     D     E   F
0  a0    b0  1.0   0.1  10.0  f0
1  a1    b1  2.0  10.2  19.0  f1
2  a1    b2  NaN  11.4  32.0  g2
3  a2    b2  3.0   8.9  25.0  f3
4  a3    b3  4.0   9.1   8.0  f4
5  a4  None  5.0  12.0   NaN  f5

In [111]:
df.isnull()

A      B      C      D      E      F
0  False  False  False  False  False  False
1  False  False  False  False  False  False
2  False  False   True  False  False  False
3  False  False  False  False  False  False
4  False  False  False  False  False  False
5  False   True  False  False   True  False

In [112]:
df.dropna()

A   B    C     D     E   F
0  a0  b0  1.0   0.1  10.0  f0
1  a1  b1  2.0  10.2  19.0  f1
3  a2  b2  3.0   8.9  25.0  f3
4  a3  b3  4.0   9.1   8.0  f4

#删除某行空值

In [113]:
df.dropna(subset=['B'])

A   B    C     D     E   F
0  a0  b0  1.0   0.1  10.0  f0
1  a1  b1  2.0  10.2  19.0  f1
2  a1  b2  NaN  11.4  32.0  g2
3  a2  b2  3.0   8.9  25.0  f3
4  a3  b3  4.0   9.1   8.0  f4

#重复值

In [114]:
df.duplicated(['A'])

0    False
1    False
2     True
3    False
4    False
5    False
dtype: bool

#必须ab同时重复

In [115]:
df.duplicated(['A','B'])

0    False
1    False
2    False
3    False
4    False
5    False
dtype: bool

#删除重复，keep= first，last，False， inplace=Boolean，是否修改原表

In [116]:
df.drop_duplicates(['A'],keep='first')

A     B    C     D     E   F
0  a0    b0  1.0   0.1  10.0  f0
1  a1    b1  2.0  10.2  19.0  f1
3  a2    b2  3.0   8.9  25.0  f3
4  a3    b3  4.0   9.1   8.0  f4
5  a4  None  5.0  12.0   NaN  f5

In [117]:
df.fillna('b*')

A   B   C     D   E   F
0  a0  b0   1   0.1  10  f0
1  a1  b1   2  10.2  19  f1
2  a1  b2  b*  11.4  32  g2
3  a2  b2   3   8.9  25  f3
4  a3  b3   4   9.1   8  f4
5  a4  b*   5  12.0  b*  f5

In [118]:
df.fillna(df['E'].mean())   #此时mean（）会忽视异常值空值

A     B     C     D     E   F
0  a0    b0   1.0   0.1  10.0  f0
1  a1    b1   2.0  10.2  19.0  f1
2  a1    b2  18.8  11.4  32.0  g2
3  a2    b2   3.0   8.9  25.0  f3
4  a3    b3   4.0   9.1   8.0  f4
5  a4  18.8   5.0  12.0  18.8  f5

插值interpolate，只能用在series
在头，插下一个，尾插上一个，中间取上下平均值

In [119]:
df['E'].interpolate()

0    10.0
1    19.0
2    32.0
3    25.0
4     8.0
5     8.0
Name: E, dtype: float64

In [120]:
pd.Series([1,None,4,5,20]).interpolate()

0     1.0
1     2.5
2     4.0
3     5.0
4    20.0
dtype: float64

#3次样条插值

In [121]:
df['E'].interpolate(method='spline',order=3)

0    10.000000
1    19.000000
2    32.000000
3    25.000000
4     8.000000
5   -20.143603
Name: E, dtype: float64

In [122]:
df

A     B    C     D     E   F
0  a0    b0  1.0   0.1  10.0  f0
1  a1    b1  2.0  10.2  19.0  f1
2  a1    b2  NaN  11.4  32.0  g2
3  a2    b2  3.0   8.9  25.0  f3
4  a3    b3  4.0   9.1   8.0  f4
5  a4  None  5.0  12.0   NaN  f5

In [123]:
upper_q = df['D'].quantile(0.75)
lower_q = df['D'].quantile(0.25)

In [124]:
q_int = upper_q - lower_q

In [125]:
k = 1.5

In [126]:
df[df['D']>lower_q-k*q_int][df['D']<upper_q+k*q_int]

c:\python36\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """Entry point for launching an IPython kernel.


A     B    C     D     E   F
1  a1    b1  2.0  10.2  19.0  f1
2  a1    b2  NaN  11.4  32.0  g2
3  a2    b2  3.0   8.9  25.0  f3
4  a3    b3  4.0   9.1   8.0  f4
5  a4  None  5.0  12.0   NaN  f5

In [127]:
df

A     B    C     D     E   F
0  a0    b0  1.0   0.1  10.0  f0
1  a1    b1  2.0  10.2  19.0  f1
2  a1    b2  NaN  11.4  32.0  g2
3  a2    b2  3.0   8.9  25.0  f3
4  a3    b3  4.0   9.1   8.0  f4
5  a4  None  5.0  12.0   NaN  f5

In [128]:
df.drop(2)

A     B    C     D     E   F
0  a0    b0  1.0   0.1  10.0  f0
1  a1    b1  2.0  10.2  19.0  f1
3  a2    b2  3.0   8.9  25.0  f3
4  a3    b3  4.0   9.1   8.0  f4
5  a4  None  5.0  12.0   NaN  f5

In [129]:
df[[True if item.startswith('f') else False for item in list(df['F'].values)]]

A     B    C     D     E   F
0  a0    b0  1.0   0.1  10.0  f0
1  a1    b1  2.0  10.2  19.0  f1
3  a2    b2  3.0   8.9  25.0  f3
4  a3    b3  4.0   9.1   8.0  f4
5  a4  None  5.0  12.0   NaN  f5

## 标注，标签，label

### 特征预处理

特征选择: 剔除与标注不相关或者冗余的特征   (剔除排序靠后的特征,进行降维)  

过滤思想

rfe算法,包裹思想  

嵌入思想  





### 特征选择

In [130]:
df=pd.DataFrame({'A':ss.norm.rvs(size=10,),
                 'B':ss.norm.rvs(size=10),
                 'C':ss.norm.rvs(size=10),
                 'D':np.random.randint(low=0,high=2,size=10)})   #最小可以取到,最大取不到
df

A         B         C  D
0 -0.107699 -0.107962 -0.070004  1
1  1.318411 -0.028930  1.113092  0
2 -0.736282  0.064627 -0.526392  0
3 -0.568904 -0.191559  0.093452  0
4 -1.128570  0.360158 -0.858875  1
5  0.827364  0.598984  1.592643  0
6  0.415531 -1.638903 -0.784411  0
7 -1.011566 -0.140195  0.587180  1
8  0.692245 -0.725933 -0.367121  0
9 -0.736100  0.423970  0.729644  0

In [131]:
from sklearn.svm import SVR
from sklearn.tree import  DecisionTreeRegressor

In [132]:
X = df.loc[:,['A','B','C']]
Y = df.loc[:,'D']

In [133]:
from sklearn.feature_selection import  SelectKBest,RFE,SelectFromModel   #过滤包裹嵌入常用类

In [134]:
skb = SelectKBest(k=2)     #保留两个特征
skb.fit(X,Y)

SelectKBest(k=2, score_func=<function f_classif at 0x000001DEAC076378>)

In [135]:
skb.transform(X)     #一个被舍弃了

array([[-0.10769867, -0.07000363],
       [ 1.31841136,  1.11309219],
       [-0.73628204, -0.52639175],
       [-0.56890394,  0.09345199],
       [-1.12857033, -0.85887465],
       [ 0.82736364,  1.59264333],
       [ 0.41553099, -0.78441114],
       [-1.01156595,  0.58718017],
       [ 0.69224452, -0.36712076],
       [-0.7361    ,  0.72964377]])

In [136]:
#线性回归器,
rfe = RFE(estimator=SVR(kernel='linear'),n_features_to_select=2,step=1)   
#                                               特征数量      每次去掉一个
rfe.fit_transform(X,Y)

array([[-0.10796227, -0.07000363],
       [-0.0289304 ,  1.11309219],
       [ 0.06462653, -0.52639175],
       [-0.19155918,  0.09345199],
       [ 0.3601584 , -0.85887465],
       [ 0.59898371,  1.59264333],
       [-1.63890262, -0.78441114],
       [-0.1401951 ,  0.58718017],
       [-0.72593282, -0.36712076],
       [ 0.42396986,  0.72964377]])

In [137]:
sfm = SelectFromModel(estimator=DecisionTreeRegressor(),threshold=0.1)
sfm.fit_transform(X,Y)

array([[-0.10769867, -0.07000363],
       [ 1.31841136,  1.11309219],
       [-0.73628204, -0.52639175],
       [-0.56890394,  0.09345199],
       [-1.12857033, -0.85887465],
       [ 0.82736364,  1.59264333],
       [ 0.41553099, -0.78441114],
       [-1.01156595,  0.58718017],
       [ 0.69224452, -0.36712076],
       [-0.7361    ,  0.72964377]])

In [138]:
sfm = SelectFromModel(estimator=DecisionTreeRegressor(),threshold=0.5)
sfm.fit_transform(X,Y)

array([[-0.10769867],
       [ 1.31841136],
       [-0.73628204],
       [-0.56890394],
       [-1.12857033],
       [ 0.82736364],
       [ 0.41553099],
       [-1.01156595],
       [ 0.69224452],
       [-0.7361    ]])

In [139]:
sfm = SelectFromModel(estimator=DecisionTreeRegressor(),threshold=0.001)
sfm.fit_transform(X,Y)

array([[-0.10769867, -0.07000363],
       [ 1.31841136,  1.11309219],
       [-0.73628204, -0.52639175],
       [-0.56890394,  0.09345199],
       [-1.12857033, -0.85887465],
       [ 0.82736364,  1.59264333],
       [ 0.41553099, -0.78441114],
       [-1.01156595,  0.58718017],
       [ 0.69224452, -0.36712076],
       [-0.7361    ,  0.72964377]])

### 特征变换


- 对指化   
 softmax   
 指数化,差距变大,归一化差距变小   
 对数化,差距变小,  
 numpy.log numpy.exp  

- 离散化  
 将连续变量分成几段(bins)  
 克服数据缺陷,某些算法要求,非线数据映射  
 分箱  
 深度:数据个数  
 宽度:数的区间  
 
  


In [140]:
lst = [6,8,10,15,16,25,40,67,32]

#等深分箱

In [141]:
pd.qcut(lst,q=3)

[(5.999, 13.333], (5.999, 13.333], (5.999, 13.333], (13.333, 27.333], (13.333, 27.333], (13.333, 27.333], (27.333, 67.0], (27.333, 67.0], (27.333, 67.0]]
Categories (3, interval[float64]): [(5.999, 13.333] < (13.333, 27.333] < (27.333, 67.0]]

In [142]:
pd.qcut(lst,q=3,labels=['low','medium','high'])

[low, low, low, medium, medium, medium, high, high, high]
Categories (3, object): [low < medium < high]

#等宽分箱

In [143]:
pd.cut(lst,bins=3)

[(5.939, 26.333], (5.939, 26.333], (5.939, 26.333], (5.939, 26.333], (5.939, 26.333], (5.939, 26.333], (26.333, 46.667], (46.667, 67.0], (26.333, 46.667]]
Categories (3, interval[float64]): [(5.939, 26.333] < (26.333, 46.667] < (46.667, 67.0]]

In [144]:
pd.cut(lst,bins=3,labels=['low','medium','high'])

[low, low, low, low, low, low, medium, high, medium]
Categories (3, object): [low < medium < high]

- 归一化,标准化  
 标准化Z-score  ,标准正态分布,



In [145]:
from sklearn.preprocessing import MinMaxScaler,StandardScaler   #引入相关模块

In [146]:
#归一化
MinMaxScaler().fit_transform(np.array([1,4,10,15,21]).reshape(-1,1))

c:\python36\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int32 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


array([[ 0.  ],
       [ 0.15],
       [ 0.45],
       [ 0.7 ],
       [ 1.  ]])

In [147]:
#标准化
StandardScaler().fit_transform(np.array([1,1,1,1,0,0,0,0,]).reshape(-1,1))

c:\python36\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int32 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


array([[ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.]])

In [148]:
StandardScaler().fit_transform(np.array([1,0,0,0,0,0,0,0,]).reshape(-1,1))

c:\python36\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int32 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


array([[ 2.64575131],
       [-0.37796447],
       [-0.37796447],
       [-0.37796447],
       [-0.37796447],
       [-0.37796447],
       [-0.37796447],
       [-0.37796447]])

- 数值化   
 定类,定序,定距,定比

 定序数值化,标签化  
 label encode   
 比如:  
 down   0  
 up     1  

定类数据,数值化,独热
one-hot encode  
red [1000]  
yuellow [0100]  
blue [0010]  
grey [0001]  

In [149]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder


In [150]:
LabelEncoder().fit_transform(np.array(['Down','Up','Up','Down']))

array([0, 1, 1, 0], dtype=int64)

In [151]:
LabelEncoder().fit_transform(np.array(['Low','High','High','Low','Medium']))
#这里按首字母排序

array([1, 0, 0, 1, 2], dtype=int64)

In [152]:
lb_encoder = LabelEncoder()
lb_tran_f = lb_encoder.fit_transform(np.array(['Red','Yellow','Blue','Green']))
lb_tran_f

array([2, 3, 0, 1], dtype=int64)

In [153]:
oht_encoder = OneHotEncoder().fit(lb_tran_f)
#这里会报一个警告,不要慌

ValueError: Expected 2D array, got 1D array instead:
array=[ 2.  3.  0.  1.].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [155]:
oht_encoder = OneHotEncoder().fit(lb_tran_f.reshape(-1,1))

In [156]:
oht_encoder.transform(lb_encoder.transform(
    np.array(['Yellow','Blue','Green','Green','Red'])).reshape(-1,1))

<5x4 sparse matrix of type '<class 'numpy.float64'>'
	with 5 stored elements in Compressed Sparse Row format>

In [157]:
oht_encoder.transform(lb_encoder.transform(
    np.array(['Yellow','Blue','Green','Green','Red'])).reshape(-1,1)).toarray()

array([[ 0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.]])

#每个颜色都变成了4个特征的形式

- 正规化(规范化)

 L1 L2 正规化

In [158]:
from sklearn.preprocessing import Normalizer
Normalizer(norm='l1').fit_transform([1,1,3,-1,2])

ValueError: Expected 2D array, got 1D array instead:
array=[ 1  1  3 -1  2].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [159]:
Normalizer(norm='l1').fit_transform(np.array([1,1,3,-1,2]).reshape(-1,1))

array([[ 1.],
       [ 1.],
       [ 1.],
       [-1.],
       [ 1.]])

#正规化是按行正规化的,所以用下面

In [160]:
Normalizer(norm='l1').fit_transform(np.array([[1,1,3,-1,2]]))

array([[ 0.125,  0.125,  0.375, -0.125,  0.25 ]])

###  特征降维

PCA降维,无监督的降维方法  
<br>
LDA降维,线性判别式分析   
lda核心: 投影变化后同一标注内距离尽可能小,不同标注间距离尽可能大




In [161]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

In [162]:
X = np.array([[-1,-1],[-2,-1],[-3,-2],[1,1],[2,1],[3,2]])

In [163]:
Y = np.array([1,1,1,2,2,2])

In [164]:
LinearDiscriminantAnalysis(n_components=1).fit_transform(X,Y)
#                           降到1维

array([[-1.73205081],
       [-1.73205081],
       [-3.46410162],
       [ 1.73205081],
       [ 1.73205081],
       [ 3.46410162]])

In [165]:
#也可以当做fisher classifier分类器来使用
src = LinearDiscriminantAnalysis().fit(X,Y)

src.predict([[0.8,1]])

array([2])

### 特征衍生  
分析特征,从各个角度衍生出特征之间的相关关系,来进行数据分析

# HR表的特征预处理  
字段说明:  
left：是否离职  
satisfaction_level：满意度  
last_evaluation：绩效评估  
number_project：完成项目数  
average_montly_hours：平均每月工作时间  
time_spend_company：为公司服务的年限  
work_accident：是否有工作事故  
promotion：过去5 年是否有升职  
salary：薪资水平  

In [216]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler,StandardScaler
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
from sklearn.preprocessing import Normalizer
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.decomposition import PCA

#sl:satisfaction_level -False:MinMax;True:Stands
#le:last_evaluation----False:MinMax;True:Stands
#npr:number_project----False:MinMax;True:Stands
#amh:average_monthly_hours---False:MinMax;True:Stands
#tsc:time_spend_company----False:MinMax;True:Stands
#wa:work_acdient----False:MinMax;True:Stands
#pl5:promotion_last_5years----False:MinMax;True:Stands

#dp:department--False:LabelEncoding;True:OneHotEncoder
#slr:salary--False:LabelEncoding;True:OneHotEncoder


def hr_preprocessing(sl=False,le=False,npr=False,amh=False,
                     tsc=False,wa=False,pl5=False,slr=False,dp=False,lower_d=False,ld_n=1):
    df = pd.read_csv('./data/HR.csv')

    #1.清洗数据
    df.dropna(subset=['satisfaction_level','last_evaluation'])
    df = df[df['satisfaction_level']<=1][df['salary']!='nme']
    #2.得到标注
    label = df['left']
    df = df.drop('left',axis = 1)
    #3.特征选择
     #特征较少,先保留所有的
    #4.特征处理
      #这里有三种选择(不处理,转为0-1,转为正态,)
    scaler_lst = [sl,le,npr,amh,tsc,wa,pl5]  
    column_lst = ['satisfaction_level','last_evaluation','number_project',
                  'average_monthly_hours','time_spend_company','Work_accident','promotion_last_5years']
    for i in range(len(scaler_lst)):
        if not scaler_lst[i]:
            df[column_lst[i]]=\
                MinMaxScaler().fit_transform(df[column_lst[i]].values.reshape(-1,1)).reshape(1,-1)[0]
        else:
            df[column_lst[i]]=\
                StandardScaler().fit_transform(df[column_lst[i]].values.reshape(-1,1)).reshape(1,-1)[0]
    scaler_lst = [slr,dp]
    column_lst = ["salary","department"]
    for i in range(len(scaler_lst)):
        if not scaler_lst[i]:
            if column_lst[i] == 'salary':
                df[column_lst[i]]=[map_salary(s) for s in df['salary'].values]
            else:
                df[column_lst[i]]=LabelEncoder().fit_transform(df[column_lst[i]])
            df[column_lst[i]]=MinMaxScaler().fit_transform(df[column_lst[i]].values.reshape(-1,1)).reshape(1,-1)[0]
        else:
            df=pd.get_dummies(df,columns=[column_lst[i]])   #one-hot
    if lower_d:
        return PCA(n_components=ld_n).fit_transform(df.values)
    
    
    return df,label
d = dict([('low',0),('medium',1),('high',2)])
def map_salary(s):
    return d.get(s,0)

hr_preprocessing(sl=True,le=True,dp=True,lower_d=False,ld_n=3)

c:\python36\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


(       satisfaction_level  last_evaluation  number_project  \
 0               -0.936495        -1.087275             0.0   
 1                0.752814         0.840707             0.6   
 2               -2.022479         0.957554             1.0   
 3                0.431041         0.899131             0.6   
 4               -0.976716        -1.145699             0.0   
 5               -0.815830        -1.262546             0.0   
 6               -2.062701         0.314894             0.8   
 7                1.235474         0.782283             0.6   
 8                1.114809         1.658639             0.6   
 9               -0.775608        -1.087275             0.0   
 10              -0.654943        -1.028852             0.0   
 11              -2.022479         0.548588             0.8   
 12               0.913701         1.191249             0.4   
 13              -0.815830        -0.970428             0.0   
 14              -1.016938        -0.912004            

- 数据清洗  
 数据样本抽样  
 异常值处理  
- 特征预处理  
 特征选择  
 特征变换  
 特征降维  
 特征衍生  